
  - name: gather ios facts
    ios_facts: 
      gather_subset: all
    register: ios_details

  - name: BACKUP THE CONFIG
    ios_config:
      backup: true
    register: config_output

  - name: SHOW CONFIG OUTPUT
    debug:
      var: config_output

  - name: RENAME BACKUP
    copy:
      src: "{{config_output.backup_path}}"
      dest: "{{ project_path }}/roles/{{ backup_role }}/backup/rtr_backup_{{ ansible_net_serialnum }}.cfg"

  - name: REMOVE NON CONFIG LINES
    lineinfile:
      path: "{{ project_path }}/roles/{{ backup_role }}/backup/rtr_backup_{{ ansible_net_serialnum }}.cfg"
      line: "Building configuration..."
      state: absent

  - name: REMOVE NON CONFIG LINES - REGEXP
    lineinfile:
      path: "{{ project_path }}/roles/{{ backup_role }}/backup/rtr_backup_{{ ansible_net_serialnum }}.cfg"
      regexp: 'Current configuration.*'
      state: absent
