- name: Create Advanced directory on server
  file:
    path: /usr/share/nginx/html/advanced/
    state: directory

- name: Copy Advanced lab guides to server
  copy:
    src: docs/adv_guide/
    dest: /usr/share/nginx/html/advanced/
  register: copycontent

- name: Build Advanced HTML Docs
  command: asciidoc -d book -v -o {{ item }}.html {{ item }}.adoc
  args:
    chdir: /usr/share/nginx/html/advanced/
  with_items:
    - index
    - 01_conditionals_lab
    - 02_jinja_lab
    - 03_filtering_lab
#    - 04_vault_lab
#    - 05_containers_lab
#    - 04_api_lab
  when: copycontent.changed