---

- name: GitLab Post | Obtain Access Token
  uri:
    url: https://gitlab.{{ dns_domain_name }}/oauth/token
    method: POST
    validate_certs: no
    status_code: 200
    body_format: json
    headers:
      Content-Type: application/json
    body: >
      {
        "grant_type": "password",
        "username": "root",
        "password": "{{ domain_admin_password }}"
      }
  register: gitlab_access_token

- name: GitLab Post | Create local users via API
  uri:
    url: https://gitlab.{{ dns_domain_name }}/api/v4/users
    method: POST
    validate_certs: no
    status_code:
      - 200
      - 201
      - 409
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ gitlab_access_token.json.access_token }}
    body: >
      {
        "username": "{{ user_prefix }}{{ item }}",
        "password": "{{ users_password }}",
        "name": "{{ user_prefix }}{{ item }}",
        "email": "{{ user_prefix }}{{ item }}@{{ dns_domain_name }}",
        "skip_confirmation": true
      }
  with_sequence: count="{{ user_count }}"

- name: GitLab Post | Get local user information via API
  uri:
    url: https://gitlab.{{ dns_domain_name }}/api/v4/users?username={{ user_prefix }}{{ item }}
    method: GET
    validate_certs: no
    status_code:
      - 200
      - 201
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ gitlab_access_token.json.access_token }}
  with_sequence: count="{{ user_count }}"
  register: gitlab_local_users

- name: GitLab Post | Create Projects via API
  uri:
    url: https://gitlab.{{ dns_domain_name }}/api/v4/projects/user/{{ item.json[0].id }}
    method: POST
    validate_certs: no
    status_code:
      - 200
      - 201
      - 409
      - 400
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ gitlab_access_token.json.access_token }}
    body: >
      {
        "name": "{{ item.json[0].name }}",
        "group": "{{ item.json[0].name }}",
        "issues_enabled": false,
        "wiki_enabled": false,
        "snippets_enabled": false
      }
  loop: "{{ gitlab_local_users.results }}"
  when: item.json is defined
