---
- name: Configure Windows User Accounts
  hosts: all
  gather_facts: false
  vars_files:
    - [ 'vars/aws.yml', 'vars/main.yml' ]
  tags:
    - windows-ad-controller
  tasks:

    - name: Add windows domain user
      win_domain_user:
        name: "{{ users_name }}"
        state: present
        enabled: yes
        account_locked: no
        groups:
          - Domain Admins
        password: "{{ users_password }}"
        update_password: on_create
        password_expired: false
        firstname: "{{ users_firstname }}"
        surname: "{{ users_surname }}"
        upn: "{{ users_upn }}"
        company: Hancock Prospecting
        email: "{{ users_upn }}@hancockprospecting.com.au"
        # path: ou=Hancock Prospecting,dc=domain,dc=local