---
- name: Configure Windows Servers
  hosts: all
  gather_facts: True
  vars_files:
    - [ 'vars/aws.yml', 'vars/main.yml' ]
  tags:
    - windows-ad-controller
  tasks:

    - include_role:
        name: ad_add_user_group