---
- name: Configure Windows Servers
  hosts: all
  gather_facts: false
  vars_files:
    - [ 'vars/aws.yml', 'vars/main.yml' ]
  tags:
    - windows-ad-controller
  tasks:

    - name: Add windows domain user
      win_domain_user:
        name: Brian
        upn: "Admin@{{ dns_domain_name }}"
        state: present
        enabled: yes
        account_locked: no
        groups:
          - Domain Admins
        password: "{{ users_password }}"
        update_password: on_create
        password_expired: false
        firstname: admin
        surname: user
        company: Hancock Prospecting
        email: "Admin@{{ dns_domain_name }}"
        # path: ou=Hancock Prospecting,dc=domain,dc=local