---
- name: Provision Instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - manage-instances
  vars:
    teardown: false
  tasks:
    - include_role:
        name: "deploy-{{ instance_loc }}-linux"

    #invoking from a workflow, then add a message for ServiceNow
    - name: set stats
      set_stats:
        data:
          snow_note: "{{ instance_loc |upper }} - {{ user_count }} Linux Servers Completed - Apache Installed - The Server is available at http://{{ ansible_host }}"
        
    # - name: Show webserver details
    #   debug: 
    #     msg: "The Server is available at http://{{ ansible_host }}"