---
- name: Configure Windows Servers
  hosts: all
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows_hosts
  tasks:
  
    # - name: Windows | Obtain windows passwords for instances
    #   ec2_win_password:
    #     region: '{{ ec2_region }}'
    #     instance_id: "{{ item.id }}"
    #     key_file: "/var/lib/awx/projects/workshops/{{ name_prefix }}/{{ skylight_user }}-{{ name_prefix }}-private.pem"
    #     wait: yes
    #     wait_timeout: 300
    #   with_items: "{{ map(attribute='tagged_instances') | list }}"
    #   register: ec2windows_password
    - include_role:
        name: windows-workstation
  # vars:
  #   ansible_password: '{{ windows_password }}'