---
- name: Configure Network Security Group
  hosts: all
  become: True
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - docs
  roles:
    - manage-azure-nsg