---
- name: Configure Windows Servers
  hosts: skylight-s1-w1
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows_hosts
  roles:
    - windows-workstation