- name: Destroy lab instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  vars:
    teardown: true
  tasks:
  - include_role:
      name: "manage-{{ instance_loc }}-instances"

  post_tasks:
   - name: Remove workshop local files
     file:
       dest: "/var/lib/awx/projects/_156__interactive/workshops/{{ name_prefix }}"
       state: absent
