---
- name: ServiceNow Notification
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    - name: Update ServiceNow ticket to indicate start
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        table: sc_request
        number: "{{ snow_request }}"
        data: 
          work_notes: "{{ snow_note }}"
      register: snow_var