---
- name: ServiceNow Notification
  hosts: all
  connection: local
  gather_facts: no
  
  tasks:

    # - name: Show all hosts
    #   debug:
    #     msg: "{{ item }}"
    #   loop: "{{ ansible_play_batch }}"

    - name: Update ServiceNow CMDB
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        table: cmdb_ci_win_server
        data: 
          asset_tag: "{{ ec2_tag_Name }}"
          name: "{{ ec2_tag_Name }}"
          cost_center: Engineering
          os_version: 7.5.201808150
          location: "{{ ec2_placement }}"
          short_description: Provisioned for EA demo
          comments: "{{ ec2_id }}"
          change_control: Project Mgmt
          os: Windows
          model_id: Iris 5875
          ip_address: "{{ ec2_ip_address }}"
          company: ACME Australia
          assigned_to: Brian Stinehart
      register: snow_var