---
- name: Snow Notification
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    - name: Update Service Now CMDB
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        table: cmdb_ci_linux_server
        # number: e7e0ebd3db925010af758a1848961957
        data: 
          asset_tag: EA-s1-WebServer
          cost_center: Projects
          os_version: 7.5.201808150
          location: australiasoutheast
          mac_address: 00-22-48-D3-EB-F5
      register: snow_var