---
- name: Run PowerShell Script
  hosts: tower
  gather_facts: True
  vars_files:
    - [ 'vars/vmware.yml' ]
  ansible_connection: vmware_tools
  ansible_vmware_host: vcenter-ae51.rhpds.opentlc.com
  ansible_vmware_user: root
  ansible_vmware_password: r3dh4t1!
  ansible_vmware_validate_certs: no  # default is yes
  ansible_vmware_guest_path: DC01/vm/rhel7