---
- name: Provision Instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - [ 'vars/vmware.yml', 'vars/main.yml' ]
  tags:
    - manage-instances
  vars:
    teardown: false
  tasks:
  - include_role:
      name: "deploy-{{ instance_loc }}-linux"