---
# defaults file for gitlab-postconfig

# defaults file for windows-ad-controller
dns_domain_name: "example.com"

# Users and Password to Create
users_password: "MySecureP@ssword1"        # MUST FOLLOW WINDOWS AD PASSWORD RULES
users:
  - user1
  - user2

