---
- set_fact:
    user: bstineha

# - name: Get info for a single service
#   ansible.windows.win_service_info:
#     name: W3SVC
#   register: service_info

# - name: Show webserver details
#   debug: 
#     msg: "{{ ansible_host }}"

- name: IIS service info
  win_service:
    name: W3SVC
  register: iis_service_info

- name: Stop IIS service
  win_service:
    name: W3SVC
    state: stopped

- name: Restart depedent services
  win_service:
    name: WAS
    state: restarted

- name: Restart a IIS service
  win_service:
    name: W3SVC
    state: restarted

- name: Confirm that 200 OK response is returned
  uri:
    url: "http://3.25.84.236:80"
    status_code: 200