# https://github.com/cedrozor/myrtille

- name: Install IIS and .Net 4.5 on Server
  win_feature:
    name:
      - Web-Server
      - Web-WebSockets
      - NET-Framework-Core
#      - Application-Server
      - Web-Asp-Net45
      - NET-HTTP-Activation
      - NET-WCF-HTTP-Activation45
    include_management_tools: True
    state: present
  when: "'Windows 10' not in ansible_distribution"

- name: Install IIS and .Net 4.5 on Non-Server
  win_dsc:
    resource_name: WindowsOptionalFeature
    Name: "{{ item }}"
    Ensure: Enable
  when: "'Windows 10' in ansible_distribution"
  loop:
    - IIS-WebServerRole
    - IIS-WebServer
    - NetFx4Extended-ASPNET45
    - IIS-NetFxExtensibility45
    - IIS-ISAPIExtensions
    - IIS-ISAPIFilter
    - IIS-ASPNET45
    - WAS-WindowsActivationService
    - WAS-ProcessModel
    - WAS-ConfigurationAPI
    - NetFx3
    - WCF-HTTP-Activation45
    - IIS-NetFxExtensibility
    - WAS-NetFxEnvironment
    - WCF-HTTP-Activation

- name: Create temp directory
  win_file:
    path: C:\Temp\
    state: directory

- name: Check if Myrtille is downloaded
  win_stat:
    path: C:\Temp\Myrtille_2.5.5_x86_x64_Setup.exe
  register: myrtille

- name: Download Myrtille to specified path only if modified (<2.9)
  win_get_url:
    url: https://github.com/cedrozor/myrtille/releases/download/v2.5.5/Myrtille_2.5.5_x86_x64_Setup.exe
    dest: C:\Temp\Myrtille_2.5.5_x86_x64_Setup.exe
  when:
    - ansible_version.full is version('2.9', '<')
    - not myrtille.stat.exists

- name: Download Myrtille to specified path only if modified
  win_get_url:
    url: https://github.com/cedrozor/myrtille/releases/download/v2.5.5/Myrtille_2.5.5_x86_x64_Setup.exe
    dest: C:\Temp\Myrtille_2.5.5_x86_x64_Setup.exe
    follow_redirects: all
  when:
    - ansible_version.full is version('2.9', '>=')
    - not myrtille.stat.exists

- name: Extract the binary
  win_command: Myrtille_2.5.5_x86_x64_Setup.exe -o 'C:\Temp' -y
  args:
    chdir: C:\Temp\
    creates: C:\Temp\setup.exe

- name: Install Myrtille
  win_package:
    path: C:\Temp\setup.exe
    arguments: /q
    creates_path: C:\Program Files (x86)\Myrtille

- name: Disable NTLM RDP Authetication requirement
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: "{{ item }}"
    data: 0
    type: dword
  with_items:
    - SecurityLayer
    - UserAuthentication

- name: Create RDP Application
  win_iis_webapplication:
    name: student{{ hostvars[inventory_hostname].student|string }}
    site: Default Web Site
    application_pool: MyrtilleAppPool
    physical_path: C:\Program Files (x86)\Myrtille\
    state: present

