---
- name: Set resource facts
  set_fact:
    azure_resource_group:  "{{ name_prefix }}-resource"
    azure_storage_account: "{{ (name_prefix + 'storage') | lower | regex_replace('[^0-9a-z]+', '') }}"
    azure_virtual_network: "{{ name_prefix }}-network"
    azure_virtual_subnet:  "{{ (name_prefix + 'subnet')  | lower | regex_replace('[^0-9a-z]+', '') }}"

################### Destroy Instances ###################

- name: Azure | DomainController | Destroy instance
  azure_rm_virtualmachine:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix }}-dc"
    started: False
    state: absent
  with_sequence: count=1
  register: dc_jobs
  async: 7200
  poll: 0

- name: Azure | Gitlab | Destroy instance
  azure_rm_virtualmachine:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix }}-gitlab"
    started: False
    state: absent
  with_sequence: count=1
  register: gitlab_jobs
  async: 7200
  poll: 0

- name: Azure | Docs | Destroy instance
  azure_rm_virtualmachine:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix }}-docs"
    started: False
    state: absent
  with_sequence: count=1
  register: docs_jobs
  async: 7200
  poll: 0

- name: Azure | Windows | Destroy instance 1
  azure_rm_virtualmachine:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-w1'}}"
    started: False
    state: absent
  with_sequence: count={{ user_count }}
  register: windows1_jobs
  async: 7200
  poll: 0

- name: Azure | Workstation | Destroy instance
  azure_rm_virtualmachine:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-wk'}}"
    started: False
    state: absent
  with_sequence: count={{ user_count }}
  register: workstation_jobs
  async: 7200
  poll: 0

- name: Azure | Tower | Destroy instance
  azure_rm_virtualmachine:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-tower'}}"
    started: False
    state: absent
  with_sequence: count={{ user_count }}
  register: tower_jobs
  async: 7200
  poll: 0

################### Wait for Jobs ###################

- name: Wait for instance deletion to complete
  async_status: jid="{{ item.ansible_job_id }}"
  register: instances
  until: instances.finished
  retries: 600
  with_items: "{{ tower_jobs.results + gitlab_jobs.results + docs_jobs.results + windows1_jobs.results + workstation_jobs.results}}"
  ignore_errors: yes

################### Remove Network Interfaces ###################

- name: Azure | Windows | Delete network interface
  azure_rm_networkinterface:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-w101'}}" 
    state: absent
  with_sequence: count={{ user_count }}
  ignore_errors: yes

- name: Azure | Workstation | Delete network interface
  azure_rm_networkinterface:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-wk01'}}"
    state: absent
  with_sequence: count={{ user_count }}
  ignore_errors: yes

- name: Azure | Tower | Delete network interface
  azure_rm_networkinterface:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-tower01'}}"
    state: absent
  with_sequence: count={{ user_count }}
  ignore_errors: yes

- name: Azure | Gitlab | Delete network interface
  azure_rm_networkinterface:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-gitlab01'}}"
    state: absent
  ignore_errors: yes

- name: Azure | Docs | Delete network interface
  azure_rm_networkinterface:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-docs01'}}"
    state: absent
  ignore_errors: yes

- name: Azure | DC | Delete network interface
  azure_rm_networkinterface:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-dc01'}}"
    state: absent
  ignore_errors: yes

################### Remove Security Groups ###################

- name: Azure | Windows | Delete Security Group
  azure_rm_securitygroup:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-w101'}}"
    state: absent
  with_sequence: count={{ user_count }}
  ignore_errors: yes

- name: Azure | Workstation | Delete Security Group
  azure_rm_securitygroup:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-wk01'}}"
    state: absent
  with_sequence: count={{ user_count }}
  ignore_errors: yes

- name: Azure | Tower | Delete Security Group
  azure_rm_securitygroup:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-tower01'}}"
    state: absent
  with_sequence: count={{ user_count }}
  ignore_errors: yes

- name: Azure | Gitlab | Delete Security Group
  azure_rm_securitygroup:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-gitlab01'}}"
    state: absent
  ignore_errors: yes

- name: Azure | Docs | Delete Security Group
  azure_rm_securitygroup:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-docs01'}}"
    state: absent
  ignore_errors: yes

- name: Azure | DC | Delete Security Group
  azure_rm_securitygroup:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-dc01'}}"
    state: absent
  ignore_errors: yes

################### Remove Public IP Addresses ###################

- name: Azure | Windows | Delete Public IP Addresses
  azure_rm_publicipaddress:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-w101'}}"
    state: absent
  with_sequence: count={{ user_count }}
  ignore_errors: yes

- name: Azure | Workstation | Delete Public IP Addresses
  azure_rm_publicipaddress:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-wk01'}}"
    state: absent
  with_sequence: count={{ user_count }}
  ignore_errors: yes

- name: Azure | Tower | Delete Public IP Addresses
  azure_rm_publicipaddress:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-s' + item + '-tower01'}}"
    state: absent
  with_sequence: count={{ user_count }}
  ignore_errors: yes

- name: Azure | Gitlab | Delete Public IP Addresses
  azure_rm_publicipaddress:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-gitlab01'}}"
    state: absent
  ignore_errors: yes

- name: Azure | Docs | Delete Public IP Addresses
  azure_rm_publicipaddress:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-docs01'}}"
    state: absent
  ignore_errors: yes

- name: Azure | DC | Delete Public IP Addresses
  azure_rm_publicipaddress:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ name_prefix + '-dc01'}}"
    state: absent
  ignore_errors: yes

################### Remove Subnets ###################

- name: Azure | Destroy subnet
  azure_rm_subnet:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"    
    resource_group: "{{ azure_resource_group }}"    
    name: "{{ azure_virtual_subnet }}"
    virtual_network_name: "{{ azure_virtual_network }}"
    address_prefix_cidr: "{{ ptr_zone_cidr }}"     
    state: absent
  ignore_errors: yes

- name: Azure | Destroy virtual network
  azure_rm_virtualnetwork:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"    
    resource_group: "{{ azure_resource_group }}"  
    name: "{{ azure_virtual_network }}" 
    address_prefixes_cidr:
        - "{{ ptr_zone_cidr }}"
    state: absent
  ignore_errors: yes

- name: Azure | Destroy resource group
  azure_rm_resourcegroup:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"  
    name: "{{ azure_resource_group }}"
    location: "{{ azure_location }}"
    state: absent

