- name: gather router facts
  ios_facts:

- name: display version
  debug:
    msg: "The IOS version is: {{ ansible_net_version }}"

- name: display serial number
  debug:
    msg: "The serial number is:{{ ansible_net_serialnum }}"

- name: create a new user
  ios_user:
    name: Hancockadmin
    configured_password: ansible
    state: present

- name: check the startup-config against the running-config
  ios_config:
    diff_against: startup
    diff_ignore_lines:
      - ntp clock .*

- name: ensure that the desired snmp strings are present
  ios_config:
    backup: yes
    commands:
      - snmp-server community ansible-public RO
      - snmp-server community ansible-private RW
      # - snmp-server community ansible-Hancock RO
