---
- name: Set DNS search string to {{ dns_domain_name }}
  win_dns_searchsuffix:
    suffixes:
      - "{{ dns_domain_name }}"

- name: Add Ansible group to a local Administrators
  win_group_membership:
    name: Administrators
    members:
     - "{{ dns_domain_name_short }}\\Ansible Users"
    state: present

- name: Add Ansible group to a local Remote Management Users
  win_group_membership:
    name: Remote Management Users
    members:
      - "{{ dns_domain_name_short }}\\Ansible Users"
    state: present

- name: install Chocolatey
  win_chocolatey:
    name: chocolatey
    state: present

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled
  when: ansible_version.full is version_compare('2.8', '<')

- name: Install Visual Studio Code, Git, and Putty
  win_chocolatey:
    name: "{{ item }}"
    ignore_checksums: true
  with_items:
    - visualstudiocode
    - git
    - googlechrome
  register: chocolatey_packages_install
  until: chocolatey_packages_install is success
  delay: 3
  retries: 5
