---
- name: find ami id for cisco
  ec2_ami_facts:
    # owners: 679593333241
    filters:
      name: "{{ ec2_image_names['cisco'] }}"
    region: "{{ ec2_region }}"
  register: cisco_ami_find

- name: set ami ids
  set_fact:
    ec2_ami_ids:
      cisco: "{{ cisco_ami_find.images[-1].image_id | default('') }}"
      
- debug:
    var: ec2_ami_ids
  when:
    - ec2_ami_ids is defined