---
- name: find ami for windows 2016 core
  ec2_ami_facts:
    filters:
      name: "{{ ec2_image_names['win2016_core'] }}"
    region: "{{ ec2_region }}"
  register: win2016_core_ami_find

- name: find ami for windows 2016 full
  ec2_ami_facts:
    filters:
      name: "{{ ec2_image_names['win2016_full'] }}"
    region: "{{ ec2_region }}"
  register: win2016_full_ami_find

- name: find ami for windows 2019 core
  ec2_ami_facts:
    filters:
      name: "{{ ec2_image_names['win2019_core'] }}"
    region: "{{ ec2_region }}"
  register: win2019_core_ami_find

- name: find ami for windows 2019 full
  ec2_ami_facts:
    filters:
      name: "{{ ec2_image_names['win2019_full'] }}"
    region: "{{ ec2_region }}"
  register: win2019_full_ami_find

- name: set ami ids
  set_fact:
    ec2_ami_ids:
      win2016_core: "{{ win2016_core_ami_find.images[-1].image_id | default('') }}"
      win2016_full: "{{ win2016_full_ami_find.images[-1].image_id | default('') }}"
      win2019_core: "{{ win2019_core_ami_find.images[-1].image_id | default('') }}"
      win2019_full: "{{ win2019_full_ami_find.images[-1].image_id | default('') }}"
      
- debug:
    var: ec2_ami_ids
  when:
    - ec2_ami_ids is defined